# Generated by Django 3.2.5 on 2021-07-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descritption',
            new_name='description',
        ),
    ]
